name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Homebrew downloads
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/Homebrew
            /Library/Caches/Homebrew
          key: ${{ runner.os }}-brew-${{ hashFiles('.github/workflows/test.yml') }}
          restore-keys: |
            ${{ runner.os }}-brew-

      - name: Install dependencies (macOS)
        run: |
          brew update
          brew install ghostscript parallel pdfcpu
          pdfcpu version

      - name: Install linters (macOS)
        run: |
          set -euxo pipefail
          brew install shellcheck shfmt || true

      - name: Lint
        run: make lint

      - name: Smoke
        run: make smoke

      - name: Make script executable
        run: chmod +x pdf-squeeze

      - name: Run tests
        env:
          PDF_SQUEEZE_TEST_JOBS: "4"
        run: make test

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-macos
          path: tests/build/logs

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        env:
          PDFCPU_VER: v0.7.1
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y ghostscript parallel curl tar
          # Install pdfcpu (pinned version; avoids GitHub API rate limits)
          url="https://github.com/pdfcpu/pdfcpu/releases/download/${PDFCPU_VER}/pdfcpu_${PDFCPU_VER#v}_Linux_x86_64.tar.gz"
          curl -L "$url" -o pdfcpu.tgz
          tar -xzf pdfcpu.tgz
          sudo mv pdfcpu*/pdfcpu /usr/local/bin/pdfcpu
          pdfcpu version

      - name: Make script executable
        run: chmod +x pdf-squeeze

      - name: Install linters (Linux)
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y shellcheck
          # shfmt (golang based)
          curl -sSLo /usr/local/bin/shfmt https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_linux_amd64
          sudo chmod +x /usr/local/bin/shfmt

      - name: Lint
        run: make lint

      - name: Smoke
        run: make smoke

      - name: Run tests
        env:
          PDF_SQUEEZE_TEST_JOBS: "4"
        run: make test

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-linux
          path: tests/build/logs

